server {
    listen 10000;
    root /usr/share/nginx/html;
    index index.html;

    resolver 8.8.8.8 valid=30s;

    location /api/auth {
        proxy_pass https://ecommerce-auth-service-3hd3.onrender.com;
        proxy_set_header Host ecommerce-auth-service-3hd3.onrender.com;
        proxy_ssl_server_name on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
    }

    location /api/products {
        proxy_pass https://ecommerce-product-service-ih9z.onrender.com;
        proxy_set_header Host ecommerce-product-service-ih9z.onrender.com;
        proxy_ssl_server_name on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
    }

    location /api/categories {
        proxy_pass https://ecommerce-product-service-ih9z.onrender.com;
        proxy_set_header Host ecommerce-product-service-ih9z.onrender.com;
        proxy_ssl_server_name on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
    }

    location /api/cart {
        proxy_pass https://ecommerce-order-service-3epz.onrender.com;
        proxy_set_header Host ecommerce-order-service-3epz.onrender.com;
        proxy_ssl_server_name on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
    }

    location /api/orders {
        proxy_pass https://ecommerce-order-service-3epz.onrender.com;
        proxy_set_header Host ecommerce-order-service-3epz.onrender.com;
        proxy_ssl_server_name on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}